### ISSUE TITLE
tox 4.x and tox-pyenv: ImportError: cannot import name 'hookimpl' from 'tox'

### ISSUE THREAD

**Issue by ModeSevenIndustrialSolutions** [samstav/tox-pyenv#22]
Looks like the current release 1.1.0 does NOT play nicely with tox 4.x.

In addition to the bug documented here:
https://github.com/tox-dev/tox-pyenv/issues/21

On adding the "py" package, the next error uncovered is:

(tox) root@9cb1a471f174:~# tox --version
ROOT: No tox.ini or setup.cfg or pyproject.toml found, assuming empty tox.ini at /root
Traceback (most recent call last):
  File "/root/tox/bin/tox", line 8, in <module>
    sys.exit(run())
  File "/root/tox/lib/python3.8/site-packages/tox/run.py", line 19, in run
    result = main(sys.argv[1:] if args is None else args)
  File "/root/tox/lib/python3.8/site-packages/tox/run.py", line 38, in main
    state = setup_state(args)
  File "/root/tox/lib/python3.8/site-packages/tox/run.py", line 53, in setup_state
    options = get_options(*args)
  File "/root/tox/lib/python3.8/site-packages/tox/config/cli/parse.py", line 38, in get_options
    guess_verbosity, log_handler, source = _get_base(args)
  File "/root/tox/lib/python3.8/site-packages/tox/config/cli/parse.py", line 61, in _get_base
    MANAGER.load_plugins(source.path)
  File "/root/tox/lib/python3.8/site-packages/tox/plugin/manager.py", line 83, in load_plugins
    self._register_plugins(inline)
  File "/root/tox/lib/python3.8/site-packages/tox/plugin/manager.py", line 37, in _register_plugins
    self.manager.load_setuptools_entrypoints(NAME)
  File "/root/tox/lib/python3.8/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/tox/lib/python3.8/site-packages/tox_pyenv.py", line 48, in <module>
    from tox import hookimpl as tox_hookimpl
ImportError: cannot import name 'hookimpl' from 'tox' (/root/tox/lib/python3.8/site-packages/tox/__init__.py)

**Comment by Warchant** [comment]
I was able to solve it:
https://warchantua.hashnode.dev/how-to-use-tox-4-with-pyenv-and-poetry
